version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"
    command: >
      sh -c "
      if [ ! -f .env ]; then cp .env.example .env; fi;
      php artisan key:generate;
      echo 'Waiting for database...';
      sleep 15;
      echo 'Running migrations...';
      php artisan migrate --force || echo 'Migration failed, but moving on...';
      echo 'Starting server...';
      php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: mysql:8.0
    container_name: PPLSI4709B_db
    environment:
      MYSQL_DATABASE: PPLSI4709B_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: PPLSI4709B_db
      MYSQL_PASSWORD: KELOMPOK_B
    ports:
      - "3308:3306"